@startuml 
hide footbox

title Gestion de sessions live

participant "Client PLX Follower - Julia" as follower
participant "Client PLX Leader - Jack" as leader
participant "Serveur PLX" as server

' Before
follower -> follower: Générer et persister\nclient_id => 7ke9A1Idkk
leader -> leader: Générer et persister\nclient_id => EUtqpL7GjC

' Follower get an empty list of sessions
follower -> server: Ouvrir la connexion (TCP + WebSocket handshake)\nprotocol version = 0.1.0, client_id = 7ke9A1Idkk
follower -> server: Msg GetSessions https://github.com/prg2/prg2
server -> follower: Msg GetSessions [  ]

' Session creation
leader -> server: Ouvrir la connexion (...)
leader -> server: Msg StartSession "PRG2 Jack"
server -> leader: Msg SessionCreated "PRG2 Jack"

' Follower join
follower -> server: Msg GetSessions https://github.com/prg2/prg2
server -> follower: Msg GetSessions [ "PRG2 Jack" ]
follower -> server: Msg JoinSession https://github.com/prg2/prg2 "PRG2 Jack"
server -> follower: Msg SessionJoined
server -> leader: Msg Stats followers=1

note over follower, server: Déroulement de l'entrainement
leader -> server: Msg StopSession
server -> server: Vérification que le client\nest bien le créateur\nde la session
server -> leader: Msg SessionStopped
server -> leader: Fermeture de la connexion
server -> follower: Msg SessionStopped
server -> follower: Fermeture de la connexion

' Ces IDs doivent rester secrète entre le client et serveur, sinon il serait possible d'impersonner un client.
' Le même client_id ne peut être utilisé sur plusieurs sockets séparés
' Les clients ne peuvent être connecté sur une session à la fois. Les messages n'ont ainsi pas besoin d'indiquer la session concernée, le serveur maintient une map de client_id vers session, et en plus socket vers client_id ?
' Les clients n'ont pas besoin d'informer sur leur nom, juste d'un ID unique qui doit être persisté afin de supporter un redémarrage du client PLX ou une reconnexion.
' Action are actions taken mostly by client, but could also be the server closing the session after inactivity or during shutdown.
' Event are responses to actions, as everything is asynchronous
' exemple messages JSON pour les 2 formats

@enduml
