@startuml 
hide footbox
skinparam defaultFontSize 16

participant "Client Follower - Julia" as follower
participant "Serveur live.plx.rs:9120" as server
participant "Client Leader - Jack" as leader
skinparam defaultFontSize 15

' Before
follower -> follower: Générer et persister\nclient_id => e9fc3566-32e3-4b98-99b5-35be520d46cb
leader <- leader: Générer et persister client_id =>\nae9b8213-fcf6-40c8-8f35-b6d14f0ace75

' Follower get an empty list of sessions
follower -> server: Ouvrir la connexion (TCP + WebSocket)\nws://live.plx.rs:9120?live_protocol_version=0.1.0\n&live_client_id=e9fc3566-32e3-4b98-99b5-35be520d46cb
follower -> server: Action GetSessions\ngroup_id=https://github.com/prg2/prg2.git
server -> follower: Event SessionsList [  ]

' Session creation
leader -> server: Ouvrir la connexion (...)
leader -> server: Action StartSession "PRG2 Jack" + group_id
server -> leader: Event SessionJoined client_num=0
' attention: pas de Stats ici !

' Follower join
follower -> server: Action GetSessions https://github.com/prg2/prg2.git
server -> follower: Event SessionsList [ "PRG2 Jack" ]
follower -> server: Action JoinSession\nhttps://github.com/prg2/prg2.git "PRG2 Jack"
server -> follower: Event SessionJoined client_num=1
server -> leader: Event Stats\nfollowers_count=1 leaders_count=1

===== Déroulement de l'entrainement ==
leader -> server: Action StopSession
server -> server: Vérification que le client\nest bien le créateur\nde la session
server -> leader: Event SessionStopped
server -> follower: Event SessionStopped

@enduml
