@startuml 
hide footbox
skinparam defaultFontSize 16

participant "Julia" as c1
participant "Serveur live.plx.rs:9120" as server
participant "Jack" as c2
participant "Jonathan" as c4
participant "Mélanie" as c3
skinparam defaultFontSize 15

===== Démarrage d'une session avec Julia, Jack et Jonathan.\nMélanie est juste connectée mais n'a pas rejoint de session. ==
server -> server: Réception signal d'arrêt
server -> c1: Event SessionStopped
server -> c1: Event ServerStopped
server -> c1: Fermeture du websocket
server -> c2: Event SessionStopped
server -> c2: Event ServerStopped
server -> c2: Fermeture du websocket
server -> c4: Event SessionStopped
server -> c4: Event ServerStopped
server -> c4: Fermeture du websocket
server -> c3: Event ServerStopped
server -> c3: Fermeture du websocket

@enduml